using System.Text.Json;
using System.Text.RegularExpressions;
using Common.Extensions;
using Common.Settings.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Notify.Models;
using WebQueries.BRP;
using WebQueries.BRP.Models;
using WebQueries.DataQuerying.Adapter.Interfaces;
using WebQueries.DataQuerying.Models.Responses;
using WebQueries.DataQuerying.Proxy.Interfaces;
using WebQueries.DataSending.Clients.Factories.Interfaces;
using WebQueries.DataSending.Clients.Interfaces;
using WebQueries.DataSending.Models.Reponses;
using WebQueries.MOBB.Interfaces;
using WebQueries.MOBB.Models;
using ZgwModels.Extensions;
using ZgwModels.Mapping.Models.POCOs.NotificatieApi;
using ZgwModels.Mapping.Models.POCOs.OpenKlant;
using ZgwModels.Mapping.Models.POCOs.OpenVtb;
using ZgwModels.Mapping.Models.POCOs.OpenZaak.Documents;
using ZgwModels.Serialization.Interfaces;

namespace WebQueries.MOBB
{
    /// <summary>
    /// Handles the "Message" scenario: fetches a message from OpenVTB,
    /// validates it, and forwards it to the MOBB / Notify API.
    /// </summary>
    public class MessageBoxScenarioImplementation : IMessageBoxScenario
    {
        private const string HardcodedMessagePostfix = " [GENERATED BY OMC]";
        private const int MaxAttachments = 2;

        private readonly IDataQueryService<NotificationEvent> _dataQuery;
        private readonly IHttpClientFactory<INotifyClient, string> _notifyClientFactory;
        private readonly ISerializationService _serializer;
        private readonly OmcConfiguration _configuration;
        private readonly IServiceProvider _serviceProvider;

        public MessageBoxScenarioImplementation(
            IDataQueryService<NotificationEvent> dataQuery,
            IHttpClientFactory<INotifyClient, string> notifyClientFactory,
            ISerializationService serializer,
            OmcConfiguration configuration,
            IServiceProvider serviceProvider)
        {
            _dataQuery = dataQuery;
            _notifyClientFactory = notifyClientFactory;
            _serializer = serializer;
            _configuration = configuration;
            _serviceProvider = serviceProvider;
        }

        /// <summary>
        /// Processes a CloudEvent by extracting the message UUID from the 'subject' field,
        /// fetching the full message from OpenVTB, validating it, and forwarding it to the MOBB API.
        /// </summary>
        /// <param name="cloudEvent">The full CloudEvent as a JsonElement.</param>
        /// <returns>An HTTP response wrapper indicating success or failure.</returns>
        public async Task<HttpRequestResponse> ProcessCloudEventAsync(JsonElement cloudEvent)
        {
            // Step 1: Extract the UUID from the CloudEvent 'subject' field
            if (!cloudEvent.TryGetProperty("subject", out JsonElement subjectElement))
            {
                return HttpRequestResponse.Failure("CloudEvent missing 'subject' property.");
            }

            string? subject = subjectElement.GetString();
            if (string.IsNullOrEmpty(subject) || !Guid.TryParse(subject, out Guid messageUuid))
            {
                return HttpRequestResponse.Failure($"Invalid UUID in 'subject': '{subject}'");
            }

            // Step 2: Create a dummy NotificationEvent to get an IQueryContext
            var dummyNotification = new NotificationEvent
            {
                MainObjectUri = new Uri($"http://temp.uri/{messageUuid}")
            };

            // Step 3: Get the query context from the dummy notification
            IQueryContext queryContext = _dataQuery.From(dummyNotification);

            // Step 4: Build the URI for the OpenVTB message endpoint
            string baseUrl = _configuration.ZGW.Endpoint.OpenVtb();
            Uri messageUri = new($"{baseUrl}/berichten/{messageUuid:D}");

            // Step 5: Fetch the VtbMessage using the context
            VtbMessage messageData = await queryContext.GetVtbMessageAsync(messageUri);

            if (string.IsNullOrWhiteSpace(messageData.MessageText))
            {
                return HttpRequestResponse.Failure("Message text is empty or missing.");
            }

            // Step 6: Resolve the recipient's BSN and OpenKlant party - needed regardless of MOBB vs. fallback
            string? recipientBsn = ExtractBsnFromUrn(messageData.RecipientUrn);
            if (recipientBsn == null)
            {
                return HttpRequestResponse.Failure("Recipient is not a citizen (BSN not found in RecipientUrn).");
            }

            CommonPartyData partyData = await queryContext.GetPartyDataAsync(caseUri: null, bsnNumber: recipientBsn);
            Guid partyId = partyData.Uri.GetGuid();

            // Step 7: Whitelist gate - applies regardless of delivery channel
            string? messageType = messageData.MessageType;
            if (string.IsNullOrEmpty(messageType) ||
                !_configuration.ZGW.Whitelist.VtbMessage_Types().IsAllowed(messageType))
            {
                return HttpRequestResponse.Failure($"MessageType '{messageType}' not allowed by whitelist.");
            }

            // Step 8: MO BB? - if not eligible, fall back to digitale post (email) or a letter
            if (!messageData.IsInMyGovernmentMessageBox)
            {
                return await SendDigitalePostFallbackAsync(cloudEvent, messageUuid, recipientBsn, partyData, partyId);
            }

            // Step 9: Append hardcoded postfix to the message text
            string modifiedMessageText = $"{messageData.MessageText}{HardcodedMessagePostfix}";

            // Step 10: Fetch attachments (maximum 2) as SingularInformationObject
            List<SingularInformationObject> documents = await FetchAttachmentsAsync(queryContext, messageData.Attachments);

            // Step 11: Build the request payload for NotifyNL/MOBB
            var notifyAttachments = documents
                .Where(document => !string.IsNullOrEmpty(document.Content) && !string.IsNullOrEmpty(document.Filename))
                .Select(document => new Attachment { file = document.Content, filename = document.Filename })
                .ToList();

            if (notifyAttachments.Count == 0)
            {
                return HttpRequestResponse.Failure("No usable attachments (with content) were found for this message.");
            }

            // Step 12: Build the reference (compressed & encoded CloudEvent + extras) and send via the MessageBox proxy
            string reference = await BuildReferenceAsync(cloudEvent, messageUuid, partyId, mobb: true);

            INotifyClient notifyClient = _notifyClientFactory.GetHttpClient(messageUuid.ToString());

            NotifySendResponse sendResponse = await notifyClient.SendMessageBoxNotificationAsync(
                recipientBsn,
                modifiedMessageText,
                messageData.Subject,
                notifyAttachments,
                reference);

            return sendResponse.IsFailure
                ? HttpRequestResponse.Failure(sendResponse.Error)
                : HttpRequestResponse.Success(
                    $"Message forwarded to MOBB. UUID: {messageUuid}, Documents: {notifyAttachments.Count}");
        }

        /// <summary>
        /// Digitale post fallback for when a message is not (or no longer) eligible for MOBB delivery:
        /// sends an email notification if the recipient has a usable email address, otherwise falls
        /// back to a letter.
        /// </summary>
        private async Task<HttpRequestResponse> SendDigitalePostFallbackAsync(
            JsonElement cloudEvent, Guid messageUuid, string recipientBsn, CommonPartyData partyData, Guid partyId)
        {
            if (string.IsNullOrEmpty(partyData.EmailAddress))
            {
                return await SendLetterFallbackAsync(recipientBsn);
            }

            Dictionary<string, object> personalization = new()
            {
                ["klant.voornaam"] = partyData.Name,
                ["klant.voorvoegselAchternaam"] = partyData.SurnamePrefix,
                ["klant.achternaam"] = partyData.Surname
            };

            string reference = await BuildReferenceAsync(cloudEvent, messageUuid, partyId, mobb: false);

            INotifyClient notifyClient = _notifyClientFactory.GetHttpClient(messageUuid.ToString());

            NotifySendResponse sendResponse = await notifyClient.SendEmailAsync(
                partyData.EmailAddress,
                _configuration.Notify.TemplateId.Email.MessageBox().ToString(),
                personalization,
                reference);

            return sendResponse.IsFailure
                ? HttpRequestResponse.Failure(sendResponse.Error)
                : HttpRequestResponse.Success("Digitale post (email) notification sent.");
        }

        /// <summary>
        /// Letter fallback for when the recipient has no usable email address. The postal address is
        /// meant to be sourced from BRP (Basisregistratie Personen) rather than OpenKlant - BRP is the
        /// intended single source of truth for postal addresses used in letters (unlike the older,
        /// name-only BRP enrichment described in docs/integraties/brp-haalcentraal.md, which predates
        /// this use case and is stale with respect to it).
        /// </summary>
        /// <remarks>
        /// Only the BRP lookup is wired up so far - two things are still blocking a real send:
        /// (1) the actual NotifyNL API is being changed by a colleague to handle attachments correctly
        ///     for letters, and the GovukNotify client fork needs a follow-up update once that lands
        ///     (see <see cref="INotifyClient.SendMessageBoxNotificationAsync"/>'s sibling, SendPrecompiledLetterAsync,
        ///     on the underlying Notify.Client.NotificationClient);
        /// (2) no sample BRP response has been verified yet, so the 'adressering'/'adresseringBinnenland'
        ///     fields aren't parsed into a postal address - the raw response is only fetched, not used.
        /// </remarks>
        private async Task<HttpRequestResponse> SendLetterFallbackAsync(string recipientBsn)
        {
            Adressering? adressering;

            try
            {
                // Resolved lazily: BrpClient's constructor throws if BRP isn't configured for this
                // environment (BRP integration is documented as optional), so this must not become a
                // hard dependency of every MessageBox notification - only of the letter fallback.
                BrpClient brpClient = _serviceProvider.GetRequiredService<BrpClient>();
                string brpResponse = await brpClient.QueryPersonAsync(recipientBsn);

                PersonenQueryResponse result = _serializer.Deserialize<PersonenQueryResponse>(brpResponse);
                adressering = result.Personen is { Count: > 0 } personen ? personen[0].Adressering : null;
            }
            catch (Exception exception)
            {
                return HttpRequestResponse.Failure(
                    $"Could not retrieve address data from BRP for the letter fallback: {exception.Message}");
            }

            // NOTE: Never include actual BRP field values (name, address lines, etc.) in a returned
            // message - BRP data must only ever be processed in memory, never logged or stored, and
            // this result can end up in logs further up the call chain.
            if (adressering is not { Adresregel1: not (null or "") })
            {
                return HttpRequestResponse.Failure("BRP returned no usable address for this recipient; cannot send a letter.");
            }

            // TODO: Generate the letter PDF from the message content + resolved adressering (aanhef,
            // aanschrijfwijze, address lines), and send it via INotifyClient.SendPrecompiledLetterAsync
            // once NotifyNL/GovukNotify support attachments correctly.
            return HttpRequestResponse.Failure(
                "Letter fallback: a postal address was resolved via BRP, but PDF generation and sending are not yet implemented.");
        }

        /// <summary>
        /// Builds the compressed &amp; Base64-encoded "reference" (CloudEvent + extras) to pass to NotifyNL.
        /// </summary>
        private async Task<string> BuildReferenceAsync(JsonElement cloudEvent, Guid messageUuid, Guid partyId, bool mobb)
        {
            var referenceData = new MessageBoxNotifyReference
            {
                CloudEvent = cloudEvent,
                MessageId = messageUuid,
                PartyId = partyId,
                Mobb = mobb
            };

            return await _serializer.Serialize(referenceData).CompressGZipAsync(CancellationToken.None);
        }

        #region Private helpers

        /// <summary>
        /// Fetches document metadata for attachments (bijlagen) from the Documenten API.
        /// Walks the attachments in order (there is no priority/ordering field, so the source's own
        /// order is trusted) and stops as soon as <see cref="MaxAttachments"/> usable ones are collected,
        /// so an invalid or ignorable entry doesn't cost a slot that a later, valid attachment could fill.
        /// </summary>
        /// <param name="queryContext">The query context for retrieving document metadata.</param>
        /// <param name="attachments">The list of attachments from the VTB message.</param>
        /// <returns>A list of <see cref="SingularInformationObject"/> containing document metadata.</returns>
        private async Task<List<SingularInformationObject>> FetchAttachmentsAsync(
            IQueryContext queryContext,
            VtbMessage.Attachment[]? attachments)
        {
            var documents = new List<SingularInformationObject>();

            if (attachments == null || attachments.Length == 0)
                return documents;

            foreach (VtbMessage.Attachment attachment in attachments)
            {
                if (documents.Count == MaxAttachments)
                    break;

                // Standard pre-uploaded attachments are not meant for the Berichtenbox
                if (attachment.IsMessageTypeAttachment)
                    continue;

                if (string.IsNullOrEmpty(attachment.InformationObjectUrn))
                    continue;

                Guid? documentUuid = ExtractUuidFromUrn(attachment.InformationObjectUrn);
                if (!documentUuid.HasValue)
                    continue;

                try
                {
                    // Fetch document metadata from Documenten API
                    SingularInformationObject document = await queryContext.GetDocumentAsync(documentUuid.Value);
                    documents.Add(document);
                }
                catch
                {
                    // Skip this attachment on failure
                    continue;
                }
            }

            return documents;
        }

        /// <summary>
        /// Extracts a 9-digit BSN from a recipient URN string.
        /// Assumes the URN contains a ':bsn:XXXXXXXXX' segment.
        /// </summary>
        private static string? ExtractBsnFromUrn(string urn)
        {
            if (string.IsNullOrEmpty(urn))
                return null;

            string[] segments = urn.Split(':');
            for (int i = 0; i < segments.Length - 1; i++)
            {
                if (string.Equals(segments[i], "bsn", StringComparison.OrdinalIgnoreCase) &&
                    Regex.IsMatch(segments[i + 1], "^[0-9]{9}$"))
                {
                    return segments[i + 1];
                }
            }

            return null;
        }

        /// <summary>
        /// Extracts a UUID from a URN string.
        /// Assumes the URN ends with ':uuid:XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX'.
        /// </summary>
        private static Guid? ExtractUuidFromUrn(string urn)
        {
            if (string.IsNullOrEmpty(urn))
                return null;

            string[] segments = urn.Split(':');
            for (int i = 0; i < segments.Length - 1; i++)
            {
                if (segments[i] == "uuid")
                {
                    string uuidStr = segments[i + 1];
                    if (Guid.TryParse(uuidStr, out Guid uuid))
                        return uuid;
                }
            }

            return null;
        }

        #endregion
    }
}