using System.Text.Json;
using System.Text.RegularExpressions;
using Common.Extensions;
using Common.Settings.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Notify.Models;
using WebQueries.BRP;
using WebQueries.BRP.Models;
using WebQueries.DataQuerying.Adapter.Interfaces;
using WebQueries.DataQuerying.Models.Responses;
using WebQueries.DataQuerying.Proxy.Interfaces;
using WebQueries.DataSending.Clients.Factories.Interfaces;
using WebQueries.DataSending.Clients.Interfaces;
using WebQueries.DataSending.Models.Reponses;
using WebQueries.MOBB.Interfaces;
using WebQueries.MOBB.Models;
using WebQueries.Tracing;
using ZgwModels.Enums;
using ZgwModels.Extensions;
using ZgwModels.Mapping.Models.POCOs.NotificatieApi;
using ZgwModels.Mapping.Models.POCOs.OpenKlant;
using ZgwModels.Mapping.Models.POCOs.OpenVtb;
using ZgwModels.Mapping.Models.POCOs.OpenZaak.Documents;
using ZgwModels.Serialization.Interfaces;

namespace WebQueries.MOBB
{
    /// <summary>
    /// Handles the "Message" scenario: fetches a message from OpenVTB,
    /// validates it, and forwards it to the MOBB / Notify API.
    /// </summary>
    public class MessageBoxScenarioImplementation : IMessageBoxScenario
    {
        private const string HardcodedMessagePostfix = " [GENERATED BY OMC]";
        private const int MaxAttachments = 2;

        /// <summary>
        /// The only Open VTB Berichten CloudEvent type that should trigger processing. Confirmed against
        /// https://github.com/maykinmedia/open-vtb/blob/main/docs/installation/cloud_events.rst: Berichten
        /// currently emits only two types, "bericht-geregistreerd" (fired on POST, before the message is
        /// necessarily available for consumption - e.g. a future publicatiedatum) and "bericht-gepubliceerd"
        /// (fired once the message is actually active). Any type other than "bericht-gepubliceerd" - including
        /// "bericht-geregistreerd" and any type Open VTB might add in the future (Taken already has 6 event
        /// types, so Berichten growing beyond 2 is plausible) - is treated as a safe no-op rather than
        /// processed, so an unrecognized future type degrades gracefully instead of being silently mishandled.
        /// </summary>
        private const string BerichtGepubliceerdType = "nl.overheid.berichten.bericht-gepubliceerd";

        private readonly IDataQueryService<NotificationEvent> _dataQuery;
        private readonly IHttpClientFactory<INotifyClient, string> _notifyClientFactory;
        private readonly ISerializationService _serializer;
        private readonly OmcConfiguration _configuration;
        private readonly IServiceProvider _serviceProvider;
        private readonly ILogger<MessageBoxScenarioImplementation> _logger;

        /// <summary>
        /// Initializes a new instance of the <see cref="MessageBoxScenarioImplementation"/> class.
        /// </summary>
        /// <param name="dataQuery">Resolves an <see cref="IQueryContext"/> for fetching Berichten/party/document data.</param>
        /// <param name="notifyClientFactory">Resolves an <see cref="INotifyClient"/> per send, keyed by message UUID.</param>
        /// <param name="serializer">(De)serializes the reference payload round-tripped through Notify NL.</param>
        /// <param name="configuration">The application configuration (whitelist, endpoints, template IDs).</param>
        /// <param name="serviceProvider">
        ///   Used to lazily resolve <see cref="BrpClient"/> only when the letter fallback is actually reached,
        ///   since BRP integration is optional and its constructor throws if not configured for this environment.
        /// </param>
        /// <param name="logger">The logger for this scenario.</param>
        public MessageBoxScenarioImplementation(
            IDataQueryService<NotificationEvent> dataQuery,
            IHttpClientFactory<INotifyClient, string> notifyClientFactory,
            ISerializationService serializer,
            OmcConfiguration configuration,
            IServiceProvider serviceProvider,
            ILogger<MessageBoxScenarioImplementation> logger)
        {
            _dataQuery = dataQuery;
            _notifyClientFactory = notifyClientFactory;
            _serializer = serializer;
            _configuration = configuration;
            _serviceProvider = serviceProvider;
            _logger = logger;
        }

        /// <summary>
        /// Processes a CloudEvent by extracting the message UUID from the 'subject' field,
        /// fetching the full message from OpenVTB, validating it, and forwarding it to the MOBB API.
        /// </summary>
        /// <param name="cloudEvent">The full CloudEvent as a JsonElement.</param>
        /// <returns>An HTTP response wrapper indicating success or failure.</returns>
        public async Task<HttpRequestResponse> ProcessCloudEventAsync(JsonElement cloudEvent)
        {
            // Step 0: Only "bericht-gepubliceerd" means the message is actually active and ready to be
            // forwarded. Everything else (including "bericht-geregistreerd" and any not-yet-existing future
            // type) is intentionally ignored here - see the BerichtGepubliceerdType doc comment.
            string cloudEventType = cloudEvent.TryGetProperty("type", out JsonElement typeElement)
                ? typeElement.GetString() ?? string.Empty
                : string.Empty;

            if (!string.Equals(cloudEventType, BerichtGepubliceerdType, StringComparison.OrdinalIgnoreCase))
            {
                _logger.LogInformation(
                    "MOBB CloudEvent type '{CloudEventType}' does not require action (only '{ExpectedType}' does); skipping.",
                    cloudEventType, BerichtGepubliceerdType);
                TraceContext.Emit("vtbcloudeventtype", "abort", $"CloudEvent type '{cloudEventType}' does not require action");
                return HttpRequestResponse.Success($"CloudEvent type '{cloudEventType}' does not require action.");
            }
            TraceContext.Emit("vtbcloudeventtype", "ok", cloudEventType);

            // Step 1: Extract the UUID from the CloudEvent 'subject' field
            if (!cloudEvent.TryGetProperty("subject", out JsonElement subjectElement))
            {
                TraceContext.Emit("vtbberichtid", "fail", "CloudEvent has no subject");
                return HttpRequestResponse.Failure("CloudEvent missing 'subject' property.");
            }

            string? subject = subjectElement.GetString();
            if (string.IsNullOrEmpty(subject) || !Guid.TryParse(subject, out Guid messageUuid))
            {
                _logger.LogWarning("MOBB CloudEvent had a missing/invalid 'subject' (expected a message UUID).");
                TraceContext.Emit("vtbberichtid", "fail", "subject is not a bericht UUID");
                return HttpRequestResponse.Failure($"Invalid UUID in 'subject': '{subject}'");
            }
            TraceContext.Emit("vtbberichtid", "ok", $"bericht {messageUuid}");

            _logger.LogInformation("Message {MessageId}: processing MOBB CloudEvent.", messageUuid);

            // Step 2: Create a dummy NotificationEvent to get an IQueryContext
            var dummyNotification = new NotificationEvent
            {
                MainObjectUri = new Uri($"http://temp.uri/{messageUuid}")
            };

            // Step 3: Get the query context from the dummy notification
            IQueryContext queryContext = _dataQuery.From(dummyNotification);

            // Step 4: Build the URI for the OpenVTB message endpoint
            string baseUrl = _configuration.ZGW.Endpoint.OpenVtb();
            Uri messageUri = new($"{baseUrl}/berichten/{messageUuid:D}");

            // Step 5: Fetch the VtbMessage using the context
            TraceContext.Emit("vtb", "start", $"Attempting to retrieve bericht {messageUuid}");
            VtbMessage messageData;
            try
            {
                messageData = await queryContext.GetVtbMessageAsync(messageUri);
            }
            catch (Exception exception)
            {
                TraceContext.Emit("vtb", "fail", exception.Message);
                throw;
            }

            TraceContext.Emit("vtb", "ok", $"bericht {messageUuid} retrieved");

            if (string.IsNullOrWhiteSpace(messageData.MessageText))
            {
                _logger.LogWarning("Message {MessageId}: text is empty/missing; dropping (no fallback).", messageUuid);
                TraceContext.Emit("vtbberichttekst", "abort", "bericht has no text");

                // Reported as a (no-op) success, like the non-actionable CloudEvent type above: this is a
                // permanent condition, so a Failure here would surface as HTTP 412 and make Open VTB
                // redeliver the same Bericht forever. Only genuinely retryable problems return Failure.
                return HttpRequestResponse.Success("Dropped: message text is empty or missing.");
            }

            TraceContext.Emit("vtbberichttekst", "ok", "bericht has text");

            // Step 6: Resolve the recipient's BSN and OpenKlant party - needed regardless of MOBB vs. fallback
            string? recipientBsn = ExtractBsnFromUrn(messageData.RecipientUrn);
            if (recipientBsn == null)
            {
                _logger.LogWarning("Message {MessageId}: recipient is not a citizen (no BSN in RecipientUrn); dropping (no fallback).", messageUuid);
                TraceContext.Emit("vtbontvanger", "abort", "recipient is not a citizen (no BSN in the recipient URN)");

                // Permanent condition - see the comment on the empty-text drop above.
                return HttpRequestResponse.Success("Dropped: recipient is not a citizen (BSN not found in RecipientUrn).");
            }

            // requireDigitalAddress: false - unlike classic ZGW scenarios (email/SMS only), MOBB has a postal
            // letter fallback for parties with zero digital addresses on file, so that must not be a hard
            // failure here; the party's identity is still resolved, just with an empty email/phone.
            //
            // createIfMissing: true - OMC's business flow does not guarantee a partij already exists for
            // this citizen, so a missing one is created on the fly rather than dropping the message.
            TraceContext.Emit("vtbontvanger", "ok", "recipient URN carries a BSN");

            TraceContext.Emit("openklant", "start", "Attempting to retrieve klant");
            CommonPartyData partyData;
            try
            {
                partyData = await queryContext.GetPartyDataAsync(caseUri: null, bsnNumber: recipientBsn, requireDigitalAddress: false, createIfMissing: true);
            }
            catch (Exception exception)
            {
                TraceContext.Emit("openklant", "fail", exception.Message);
                throw;
            }
            Guid partyId = partyData.Uri.GetGuid();
            TraceContext.Emit("openklant", "ok", "klant retrieved");

            _logger.LogDebug("Message {MessageId}: resolved recipient BSN (length {BsnLength}) to OpenKlant party {PartyId}.",
                messageUuid, recipientBsn.Length, partyId);

            // Step 7: Whitelist gate - applies regardless of delivery channel
            string? messageType = messageData.MessageType;
            if (string.IsNullOrEmpty(messageType) ||
                !_configuration.ZGW.Whitelist.VtbMessage_Types().IsAllowed(messageType))
            {
                _logger.LogWarning("Message {MessageId}: rejected by whitelist (MessageType '{MessageType}'); dropping (no fallback).",
                    messageUuid, messageType);
                TraceContext.Emit("vtbberichttype", "abort", $"berichttype '{messageType}' is not whitelisted");

                // Permanent condition - see the comment on the empty-text drop above. This mirrors the classic
                // ZGW scenarios, where a whitelist rejection raises AbortedNotifyingException (HTTP 206), not a
                // failure; that exception type lives in the EventsHandler assembly and cannot be used here.
                return HttpRequestResponse.Success($"Dropped: MessageType '{messageType}' not allowed by whitelist.");
            }

            TraceContext.Emit("vtbberichttype", "ok", $"berichttype '{messageType}' is whitelisted");

            // Step 8: MOBB? - if not eligible, fall back to digitale post (email) or a letter
            TraceContext.Emit("mobbgeschiktheid", "ok", messageData.IsInMyGovernmentMessageBox
                ? "bericht is for the Berichtenbox"
                : "not for the Berichtenbox; falling back to digitale post or a letter");
            if (!messageData.IsInMyGovernmentMessageBox)
            {
                _logger.LogInformation("Message {MessageId}: not eligible for MOBB inbox; going straight to digitale-post/letter fallback.", messageUuid);
                return await SendDigitalePostFallbackAsync(cloudEvent, messageUuid, recipientBsn, partyData, partyId, queryContext, messageData);
            }

            // Step 9: Append hardcoded postfix to the message text
            string modifiedMessageText = $"{messageData.MessageText}{HardcodedMessagePostfix}";

            // Step 10: Fetch attachments (maximum 2) as SingularInformationObject
            List<SingularInformationObject> documents = await FetchAttachmentsWithTraceAsync(queryContext, messageData.Attachments);

            // Step 11: Build the request payload for NotifyNL/MOBB
            var notifyAttachments = documents
                .Where(document => !string.IsNullOrEmpty(document.Content) && !string.IsNullOrEmpty(document.Filename))
                .Select(document => new Attachment { file = document.Content, filename = document.Filename })
                .ToList();

            // 0 to 2 attachments are allowed - an empty list proceeds normally, matching the underlying
            // GovukNotify client's own (now-relaxed) validation.
            _logger.LogDebug("Message {MessageId}: {Count} usable attachment(s) collected.", messageUuid, notifyAttachments.Count);

            // Step 12: Build the reference (compressed & encoded CloudEvent + extras) and send via the MessageBox proxy
            string reference = await BuildReferenceAsync(cloudEvent, messageUuid, partyId, mobb: true);

            INotifyClient notifyClient = _notifyClientFactory.GetHttpClient(messageUuid.ToString());

            NotifySendResponse sendResponse = await notifyClient.SendMessageBoxNotificationAsync(
                recipientBsn,
                modifiedMessageText,
                messageType,
                messageData.Subject,
                notifyAttachments,
                reference);

            if (sendResponse.IsFailure)
            {
                // BPMN: the MOBB delivery-outcome gateway ("(Permanent) Success?") -> "Nee" -> the
                // MOBB-technical-failure contactmoment step -> falls through to the same digitale-post/letter
                // fallback chain as MOBB-ineligibility.
                // TODO (treated uniformly for now, per instruction): the BPMN distinguishes "no MOBB
                // subscription" (no separate failed-attempt contactmoment, just adjusted fallback text) from
                // "technical failure" (a failed-attempt contactmoment IS created) - NotifySendResponse doesn't
                // expose enough detail to tell these apart yet. This draft does not create a separate
                // "failed MOBB attempt" contactmoment at all; it just falls through to the fallback chain.
                TraceContext.Emit("berichtenbox", "fail", $"rejected by Notify NL, falling back: {sendResponse.Error}");
                _logger.LogWarning(
                    "Message {MessageId}: MOBB send REJECTED synchronously ({Error}); falling back to digitale-post/letter. " +
                    "NOTE: unlike an async delivery-receipt failure, this synchronous rejection creates NO contactmoment record.",
                    messageUuid, sendResponse.Error);
                return await SendDigitalePostFallbackAsync(cloudEvent, messageUuid, recipientBsn, partyData, partyId, queryContext, messageData);
            }

            _logger.LogInformation("Message {MessageId}: MOBB send accepted by Notify NL; awaiting delivery-receipt callback.", messageUuid);
            TraceContext.Emit("berichtenbox", "ok", "accepted by Notify NL");

            return HttpRequestResponse.Success(
                $"Message forwarded to MOBB. UUID: {messageUuid}, Documents: {notifyAttachments.Count}");
        }

        /// <summary>
        /// Digitale post fallback for when a message is not (or no longer) eligible for MOBB delivery:
        /// sends an email notification if the recipient has a usable email address, otherwise falls
        /// back to a letter.
        /// </summary>
        private async Task<HttpRequestResponse> SendDigitalePostFallbackAsync(
            JsonElement cloudEvent, Guid messageUuid, string recipientBsn, CommonPartyData partyData, Guid partyId,
            IQueryContext queryContext, VtbMessage messageData)
        {
            if (string.IsNullOrEmpty(partyData.EmailAddress))
            {
                // BPMN: the digitale-post eligibility gateway ("Nee, geen digitale post") -> straight to letter.
                _logger.LogInformation("Message {MessageId}: no email address on file; going straight to letter fallback.", messageUuid);
                TraceContext.Emit("mobbemailadres", "abort", "no e-mail address on file; falling back to a letter");
                return await SendLetterFallbackAsync(cloudEvent, messageUuid, partyId, recipientBsn, messageData, queryContext, wasGefaaldeNotificatie: false);
            }

            TraceContext.Emit("mobbemailadres", "ok", "e-mail address on file");

            Dictionary<string, object> personalization = new()
            {
                ["klant.voornaam"] = partyData.Name,
                ["klant.voorvoegselAchternaam"] = partyData.SurnamePrefix,
                ["klant.achternaam"] = partyData.Surname
            };

            string reference = await BuildReferenceAsync(cloudEvent, messageUuid, partyId, mobb: false);

            INotifyClient notifyClient = _notifyClientFactory.GetHttpClient(messageUuid.ToString());

            NotifySendResponse sendResponse = await notifyClient.SendEmailAsync(
                partyData.EmailAddress,
                _configuration.Notify.TemplateId.Email.MessageBox().ToString(),
                personalization,
                reference);

            if (sendResponse.IsFailure)
            {
                // BPMN: the email delivery-outcome gateway ("Notificatie gelukt?") -> "Nee" -> the
                // email-failure contactmoment step (flag "Was notificatie") -> falls through to letter.
                TraceContext.Emit("notify-email", "fail", $"rejected by Notify NL, falling back to a letter: {sendResponse.Error}");
                _logger.LogWarning(
                    "Message {MessageId}: digitale-post (email) send REJECTED synchronously ({Error}); falling back to letter. " +
                    "NOTE: unlike an async delivery-receipt failure, this synchronous rejection creates NO contactmoment record.",
                    messageUuid, sendResponse.Error);
                return await SendLetterFallbackAsync(cloudEvent, messageUuid, partyId, recipientBsn, messageData, queryContext, wasGefaaldeNotificatie: true);
            }

            _logger.LogInformation("Message {MessageId}: digitale-post (email) send accepted by Notify NL; awaiting delivery-receipt callback.", messageUuid);
            TraceContext.Emit("notify-email", "ok", "digitale post accepted by Notify NL");

            return HttpRequestResponse.Success("Digitale post (email) notification sent.");
        }

        /// <summary>
        /// Letter fallback for when the recipient has no usable email address. The postal address is
        /// sourced from BRP (Basisregistratie Personen) rather than OpenKlant - BRP is the intended
        /// single source of truth for postal addresses used in letters (unlike the older, name-only
        /// BRP enrichment described in docs/integraties/brp-haalcentraal.md, which predates this use
        /// case and is stale with respect to it).
        /// </summary>
        /// <remarks>
        /// Sends via the template-based <see cref="INotifyClient.SendLetterAsync"/> (same mechanism the
        /// classic ZGW scenarios already use), with the original Bericht's own attachments (if any)
        /// carried over. This is a deliberate trade-off vs. a precompiled-PDF send: Notify NL renders the
        /// letter server-side from <see cref="GetLetterPersonalization"/>'s placeholders rather than from
        /// a PDF OMC builds itself, so no OMC-side PDF generation is needed - but the letter's layout is
        /// whatever the <c>MessageBoxLetter</c> template defines, not a copy of the Bericht's own formatting.
        /// <para>
        /// NOTE (flagged, not resolved): docs/api-documentatie/notify-nl-api-documentatie-rest.md's "Brief
        /// versturen" section is marked "(toekomstig)" with an explicit caveat that letter sending is not
        /// yet supported in the Netherlands. That doc predates the <c>POST v2/notifications/letter</c>
        /// schema this method was built against, so it may simply be stale - but if it is still accurate,
        /// a real send here will fail at the Notify NL API itself (surfaced as a normal
        /// <see cref="NotifySendResponse.IsFailure"/>, not a crash). Worth confirming with NotifyNL/the
        /// team before relying on this in production.
        /// </para>
        /// </remarks>
        private async Task<HttpRequestResponse> SendLetterFallbackAsync(
            JsonElement cloudEvent, Guid messageUuid, Guid partyId, string recipientBsn,
            VtbMessage messageData, IQueryContext queryContext, bool wasGefaaldeNotificatie)
        {
            _logger.LogInformation("Message {MessageId}: attempting letter fallback (was notificatie failed: {WasGefaaldeNotificatie}).",
                messageUuid, wasGefaaldeNotificatie);

            Adressering? adressering;

            TraceContext.Emit("brp", "start", "Attempting to retrieve the address for the letter");
            try
            {
                // Resolved lazily: BrpClient's constructor throws if BRP isn't configured for this
                // environment (BRP integration is documented as optional), so this must not become a
                // hard dependency of every MessageBox notification - only of the letter fallback.
                BrpClient brpClient = _serviceProvider.GetRequiredService<BrpClient>();
                string brpResponse = await brpClient.QueryPersonAsync(recipientBsn);

                PersonenQueryResponse result = _serializer.Deserialize<PersonenQueryResponse>(brpResponse);
                adressering = result.Personen is { Count: > 0 } personen ? personen[0].Adressering : null;
            }
            catch (Exception exception)
            {
                _logger.LogError(exception, "Message {MessageId}: BRP lookup for the letter fallback failed.", messageUuid);
                TraceContext.Emit("brp", "fail", exception.Message);
                return HttpRequestResponse.Failure(
                    $"Could not retrieve address data from BRP for the letter fallback: {exception.Message}");
            }
            TraceContext.Emit("brp", "ok", "person retrieved");

            // NOTE: Never include actual BRP field values (name, address lines, etc.) in a returned
            // message - BRP data must only ever be processed in memory, never logged or stored, and
            // this result can end up in logs further up the call chain.
            if (adressering is not { Adresregel1: not (null or "") })
            {
                _logger.LogWarning("Message {MessageId}: BRP returned no usable address; cannot send a letter.", messageUuid);
                TraceContext.Emit("brpadres", "fail", "no usable address; no channel left");
                return HttpRequestResponse.Failure("BRP returned no usable address for this recipient; cannot send a letter.");
            }

            // The address itself is never traced - BRP data stays in memory only.
            TraceContext.Emit("brpadres", "ok", "usable address");

            // Reuse the same attachment-fetching helper the MOBB send path uses (Step 10); a letter can
            // carry the same base64 file content, just without the {file, filename} shape MOBB uses.
            List<SingularInformationObject> documents = await FetchAttachmentsWithTraceAsync(queryContext, messageData.Attachments);
            List<string> attachmentContents = documents
                .Where(document => !string.IsNullOrEmpty(document.Content))
                .Select(document => document.Content!)
                .ToList();

            Dictionary<string, object> personalization = GetLetterPersonalization(adressering.Value, messageData, wasGefaaldeNotificatie);

            string reference = await BuildReferenceAsync(cloudEvent, messageUuid, partyId, mobb: false, wasGefaaldeNotificatie);

            INotifyClient notifyClient = _notifyClientFactory.GetHttpClient(messageUuid.ToString());

            NotifySendResponse sendResponse = await notifyClient.SendLetterAsync(
                _configuration.Notify.TemplateId.MessageBoxLetter().ToString(),
                personalization,
                reference,
                attachmentContents.Count > 0 ? attachmentContents : null);

            if (sendResponse.IsFailure)
            {
                // BPMN: the letter/print delivery-outcome gateway ("Gelukt?") -> "Nee - Alleen technische
                // issues" -> only a failed contactmoment is created (handled by the caller); no further
                // fallback channel exists.
                _logger.LogWarning(
                    "Message {MessageId}: letter send REJECTED synchronously ({Error}); no further fallback channel exists for this Bericht.",
                    messageUuid, sendResponse.Error);
                TraceContext.Emit("notify-post", "fail", $"rejected by Notify NL, no fallback left: {sendResponse.Error}");
                return HttpRequestResponse.Failure($"Letter send rejected: {sendResponse.Error}");
            }

            _logger.LogInformation("Message {MessageId}: letter send accepted by Notify NL; awaiting delivery-receipt callback.", messageUuid);
            TraceContext.Emit("notify-post", "ok", "letter accepted by Notify NL");

            return HttpRequestResponse.Success($"Letter notification sent. Attachments: {attachmentContents.Count}");
        }

        /// <summary>
        /// Builds the personalization dictionary for the MOBB letter fallback template from BRP's
        /// <see cref="Adressering"/> and the original Bericht's own subject/text.
        /// </summary>
        /// <remarks>
        /// <c>address_line_1</c>/<c>address_line_2</c>/<c>address_line_3</c> are Notify NL's confirmed
        /// reserved envelope-window keys, and the documented example maps them to [name, street,
        /// postcode+city] - matched here to <see cref="Adressering.Aanschrijfwijze"/>,
        /// <see cref="Adressering.Adresregel1"/>, <see cref="Adressering.Adresregel2"/> respectively.
        /// <c>bericht</c>, <c>wasMOBB</c>, and <c>wasNotificatie</c> are now CONFIRMED as the real
        /// <c>MessageBoxLetter</c> template's exact placeholder names (2026-08-18, live 400 response:
        /// "Missing personalisation: bericht, wasMOBB, wasNotificatie" - the original guesses
        /// <c>bericht.onderwerp</c>/<c>bericht.tekst</c>/<c>wasVoorMobb</c>/<c>wasGefaaldeNotificatie</c>
        /// were wrong).
        /// <para>
        /// TODO (still speculative): <c>bericht</c> is a single flat field, unlike the split subject/text
        /// used elsewhere - assumed here to be <see cref="VtbMessage.MessageText"/> alone (the letter body;
        /// the subject isn't included). Confirm this is what the template actually expects to render.
        /// </para>
        /// <para>
        /// <c>wasMOBB</c>/<c>wasNotificatie</c> are deliberately passed as booleans, not pre-rendered text:
        /// the BPMN's own annotation on this step says the letter template "moet conditionals in template
        /// hebben" (must have conditionals in the template) - e.g. Notify NL's <c>((flag??text))</c> syntax
        /// - so the Dutch upsell/reminder copy belongs in the template, not here. <c>wasMOBB</c> is
        /// unconditionally <see langword="true"/>: every letter this scenario sends is, by construction, a
        /// MOBB fallback (see <see cref="MessageBoxNotifyReference.Mobb"/>'s own remarks).
        /// </para>
        /// </remarks>
        private static Dictionary<string, object> GetLetterPersonalization(
            Adressering adressering, VtbMessage messageData, bool wasGefaaldeNotificatie)
        {
            var personalization = new Dictionary<string, object>();
            int lineIndex = 1;

            personalization[$"address_line_{lineIndex++}"] =
                adressering.Aanschrijfwijze?.Naam ?? adressering.Aanhef ?? adressering.GebruikInLopendeTekst ?? string.Empty;
            personalization[$"address_line_{lineIndex++}"] = adressering.Adresregel1 ?? string.Empty;
            personalization[$"address_line_{lineIndex++}"] = adressering.Adresregel2 ?? string.Empty;

            if (!string.IsNullOrEmpty(adressering.Adresregel3))
            {
                personalization[$"address_line_{lineIndex++}"] = adressering.Adresregel3;
            }

            if (!string.IsNullOrEmpty(adressering.Land?.Omschrijving))
            {
                personalization[$"address_line_{lineIndex}"] = adressering.Land.Value.Omschrijving!;
            }

            personalization["bericht"] = messageData.MessageText;
            personalization["wasMOBB"] = true;
            personalization["wasNotificatie"] = wasGefaaldeNotificatie;

            return personalization;
        }

        /// <summary>
        /// Continues the fallback chain from an asynchronous delivery-receipt callback reporting that a
        /// previously-accepted send actually failed to deliver. See <see cref="IMessageBoxScenario.HandleDeliveryFailureAsync"/>.
        /// </summary>
        /// <remarks>
        ///   <paramref name="failedChannel"/> comes from NotifyNL's own callback <c>Type</c> field
        ///   (via <c>callback.Type.ConvertToNotifyMethod()</c>), so it is the actual reported channel -
        ///   not something derived from <see cref="MessageBoxNotifyReference.Mobb"/>/<see cref="MessageBoxNotifyReference.WasGefaaldeNotificatie"/>,
        ///   which alone cannot distinguish "this was the e-mail fallback" from "this was the eventual
        ///   letter fallback" (both currently have <c>Mobb == false</c>).
        /// </remarks>
        public async Task<HttpRequestResponse> HandleDeliveryFailureAsync(MessageBoxNotifyReference reference, NotifyMethods failedChannel)
        {
            // codeql[cs/exposure-of-sensitive-information]: false positive - CodeQL's heuristic treats
            // NotifyMethods.Email as a sensitive-data source purely because of its "Email" name.
            // failedChannel is a channel discriminator (Mobb/Email/Letter), never an actual e-mail
            // address, so nothing PII-bearing is written to the log here.
            _logger.LogWarning("Message {MessageId}: delivery-receipt callback reported FAILURE for channel {FailedChannel}.",
                reference.MessageId, failedChannel);

            if (failedChannel == NotifyMethods.Letter)
            {
                // BPMN: the letter/print delivery-outcome gateway ("Gelukt?") -> "Nee - Alleen technische
                // issues" -> only a failed contactmoment is created (handled by the caller); the print-street
                // activity's own annotation notes it currently has no further fallback path back to OMC.
                _logger.LogWarning("Message {MessageId}: letter delivery failed; no further fallback channel exists for this Bericht.",
                    reference.MessageId);
                return HttpRequestResponse.Failure(
                    "Letter delivery failed (reported via callback); no further fallback channel exists for this Bericht.");
            }

            if (failedChannel != NotifyMethods.Mobb && failedChannel != NotifyMethods.Email)
            {
                // codeql[cs/exposure-of-sensitive-information]: false positive - see the identical
                // suppression above; failedChannel is never an actual e-mail address.
                _logger.LogWarning(
                    "Message {MessageId}: delivery-failure callback reported an unrecognized/unsupported channel ('{FailedChannel}'); no fallback attempted.",
                    reference.MessageId, failedChannel);
                return HttpRequestResponse.Failure(
                    $"Delivery failure callback reported an unrecognized/unsupported channel ('{failedChannel}') for a MOBB Bericht; no fallback was attempted.");
            }

            IQueryContext queryContext;
            VtbMessage messageData;
            string recipientBsn;
            CommonPartyData partyData;

            try
            {
                // Re-derive recipient identity from OpenVTB/OpenKlant using only the MessageId that
                // round-tripped through the reference - BSN is deliberately not stored in the reference
                // itself, matching why only PartyId (not BSN) is kept there for the OpenKlant side.
                (queryContext, messageData, recipientBsn, partyData) = await ResolveRecipientAsync(reference.MessageId);
            }
            catch (Exception exception)
            {
                _logger.LogError(exception,
                    "Message {MessageId}: could not re-resolve recipient context for the delivery-failure fallback.", reference.MessageId);
                return HttpRequestResponse.Failure(
                    $"Could not re-resolve recipient context for the delivery-failure fallback: {exception.Message}");
            }

            if (failedChannel == NotifyMethods.Mobb)
            {
                // BPMN: the MOBB delivery-outcome gateway ("(Permanent) Success?") -> "Nee" -> the
                // MOBB-technical-failure contactmoment step -> same digitale-post/letter fallback chain as
                // MOBB-ineligibility or a synchronous send failure.
                _logger.LogInformation("Message {MessageId}: MOBB delivery failed; attempting digitale-post/letter fallback.", reference.MessageId);
                return await SendDigitalePostFallbackAsync(reference.CloudEvent, reference.MessageId, recipientBsn, partyData, reference.PartyId, queryContext, messageData);
            }

            // BPMN: the email delivery-outcome gateway ("Notificatie gelukt?") -> "Nee" -> the email-failure
            // contactmoment step (flag "Was notificatie") -> falls through to letter.
            _logger.LogInformation("Message {MessageId}: digitale-post (email) delivery failed; attempting letter fallback.", reference.MessageId);
            return await SendLetterFallbackAsync(reference.CloudEvent, reference.MessageId, reference.PartyId, recipientBsn, messageData, queryContext, wasGefaaldeNotificatie: true);
        }

        /// <summary>
        /// Re-fetches the VTB message by UUID and resolves the recipient's BSN + OpenKlant party data -
        /// the same lookups <see cref="ProcessCloudEventAsync"/>'s steps 2-6 perform, factored out so a
        /// delivery-failure callback (which only carries <see cref="MessageBoxNotifyReference.MessageId"/>,
        /// not the recipient's BSN) can redo them independently. Also returns the <see cref="IQueryContext"/>
        /// and <see cref="VtbMessage"/> themselves, since a subsequent letter fallback needs both (to fetch
        /// attachments and to build personalization) and re-deriving them a second time would be wasteful.
        /// </summary>
        private async Task<(IQueryContext QueryContext, VtbMessage MessageData, string RecipientBsn, CommonPartyData PartyData)> ResolveRecipientAsync(Guid messageUuid)
        {
            var dummyNotification = new NotificationEvent
            {
                MainObjectUri = new Uri($"http://temp.uri/{messageUuid}")
            };

            IQueryContext queryContext = _dataQuery.From(dummyNotification);

            string baseUrl = _configuration.ZGW.Endpoint.OpenVtb();
            Uri messageUri = new($"{baseUrl}/berichten/{messageUuid:D}");
            VtbMessage messageData = await queryContext.GetVtbMessageAsync(messageUri);

            string? recipientBsn = ExtractBsnFromUrn(messageData.RecipientUrn);
            if (recipientBsn == null)
            {
                throw new InvalidOperationException("Recipient is not a citizen (BSN not found in RecipientUrn).");
            }

            // requireDigitalAddress: false / createIfMissing: true - see the matching comment in
            // ProcessCloudEventAsync; this callback-triggered re-resolution can also end up at the letter
            // fallback, and can equally be the first time OMC has resolved this citizen's partij.
            CommonPartyData partyData = await queryContext.GetPartyDataAsync(caseUri: null, bsnNumber: recipientBsn, requireDigitalAddress: false, createIfMissing: true);

            return (queryContext, messageData, recipientBsn, partyData);
        }

        /// <summary>
        /// Builds the compressed &amp; Base64-encoded "reference" (CloudEvent + extras) to pass to NotifyNL.
        /// </summary>
        /// <param name="cloudEvent">The full CloudEvent as a JsonElement.</param>
        /// <param name="messageUuid">The UUID of the VTB message (Bericht).</param>
        /// <param name="partyId">The resolved OpenKlant party GUID.</param>
        /// <param name="mobb">Whether this particular send actually went out via MOBB.</param>
        /// <param name="wasGefaaldeNotificatie">
        ///   Whether a digitale-post (email) attempt failed before this send happened - only meaningful
        ///   for a letter fallback reference; see <see cref="MessageBoxNotifyReference.WasGefaaldeNotificatie"/>.
        /// </param>
        private async Task<string> BuildReferenceAsync(
            JsonElement cloudEvent, Guid messageUuid, Guid partyId, bool mobb, bool wasGefaaldeNotificatie = false)
        {
            var referenceData = new MessageBoxNotifyReference
            {
                CloudEvent = cloudEvent,
                MessageId = messageUuid,
                PartyId = partyId,
                Mobb = mobb,
                WasGefaaldeNotificatie = wasGefaaldeNotificatie
            };

            return await _serializer.Serialize(referenceData).CompressGZipAsync(CancellationToken.None);
        }

        #region Private helpers

        /// <summary>
        /// Fetches document metadata for attachments (bijlagen) from the Documenten API.
        /// Walks the attachments in order (there is no priority/ordering field, so the source's own
        /// order is trusted) and stops as soon as <see cref="MaxAttachments"/> usable ones are collected,
        /// so an invalid or ignorable entry doesn't cost a slot that a later, valid attachment could fill.
        /// </summary>
        /// <param name="queryContext">The query context for retrieving document metadata.</param>
        /// <param name="attachments">The list of attachments from the VTB message.</param>
        /// <returns>A list of <see cref="SingularInformationObject"/> containing document metadata.</returns>
        /// <summary>
        /// <see cref="FetchAttachmentsAsync"/>, traced as a call to the Documenten API — only when the
        /// Bericht has attachments at all, so a Bericht without any doesn't show a call that never happens.
        /// </summary>
        private async Task<List<SingularInformationObject>> FetchAttachmentsWithTraceAsync(
            IQueryContext queryContext,
            VtbMessage.Attachment[]? attachments)
        {
            if (attachments is not { Length: > 0 })
            {
                return [];
            }

            TraceContext.Emit("documenten", "start", $"Attempting to retrieve {attachments.Length} attachment(s)");
            List<SingularInformationObject> documents = await FetchAttachmentsAsync(queryContext, attachments);
            TraceContext.Emit("documenten", "ok", $"{documents.Count} attachment(s) retrieved");

            return documents;
        }

        private async Task<List<SingularInformationObject>> FetchAttachmentsAsync(
            IQueryContext queryContext,
            VtbMessage.Attachment[]? attachments)
        {
            var documents = new List<SingularInformationObject>();

            if (attachments == null || attachments.Length == 0)
                return documents;

            foreach (VtbMessage.Attachment attachment in attachments)
            {
                if (documents.Count == MaxAttachments)
                    break;

                // Standard pre-uploaded attachments are not meant for the Berichtenbox
                if (attachment.IsMessageTypeAttachment)
                    continue;

                if (string.IsNullOrEmpty(attachment.InformationObjectUrn))
                    continue;

                Guid? documentUuid = ExtractUuidFromUrn(attachment.InformationObjectUrn);
                if (!documentUuid.HasValue)
                    continue;

                try
                {
                    // Fetch document metadata from Documenten API
                    SingularInformationObject document = await queryContext.GetDocumentAsync(documentUuid.Value);

                    // "inhoud" is a download link on GET, not the file content itself (confirmed against
                    // the live Documenten API - see SingularInformationObject.Content's remarks), so the
                    // actual bytes need a second, explicit fetch before this is usable as a Notify attachment.
                    if (!string.IsNullOrEmpty(document.Content))
                    {
                        document.Content = await queryContext.GetDocumentContentAsync(new Uri(document.Content));
                    }

                    documents.Add(document);
                }
                catch (Exception exception)
                {
                    _logger.LogWarning(exception,
                        "Skipping attachment {DocumentUuid}: failed to fetch or resolve its content.", documentUuid);
                }
            }

            return documents;
        }

        /// <summary>
        /// Extracts a 9-digit BSN from a recipient URN string.
        /// Assumes the URN contains a ':bsn:XXXXXXXXX' segment.
        /// </summary>
        private static string? ExtractBsnFromUrn(string urn)
        {
            if (string.IsNullOrEmpty(urn))
                return null;

            string[] segments = urn.Split(':');
            for (int i = 0; i < segments.Length - 1; i++)
            {
                if (string.Equals(segments[i], "bsn", StringComparison.OrdinalIgnoreCase) &&
                    Regex.IsMatch(segments[i + 1], "^[0-9]{9}$"))
                {
                    return segments[i + 1];
                }
            }

            return null;
        }

        /// <summary>
        /// Extracts a UUID from a URN string.
        /// Assumes the URN ends with ':uuid:XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX'.
        /// </summary>
        private static Guid? ExtractUuidFromUrn(string urn)
        {
            if (string.IsNullOrEmpty(urn))
                return null;

            string[] segments = urn.Split(':');
            for (int i = 0; i < segments.Length - 1; i++)
            {
                if (segments[i] == "uuid")
                {
                    string uuidStr = segments[i + 1];
                    if (Guid.TryParse(uuidStr, out Guid uuid))
                        return uuid;
                }
            }

            return null;
        }

        #endregion
    }
}