name: Post-merge actions

on:
  pull_request:
    branches: ["main"]
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # Don't want the tests running in parallel
  cancel-in-progress: true

jobs:
  validate-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Europe/Amsterdam"
        name: Set Timezone to Europe/Amsterdam

      - uses: actions/checkout@v4
        name: Checkout repository

      - run: |
          LATEST_RELEASE=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r '.tag_name' | sed 's/^v\.//')
          version_release=$LATEST_RELEASE >> $GITHUB_OUTPUT
        name: Get latest release and strip prefix
        id: release

      - run: |
          PROJECT_VERSION=$(grep -oPm1 "(?<=<VersionPrefix>)[^<]+" OMC/Infrastructure/WebApi/EventsHandler/EventsHandler.csproj)
          version_project=$PROJECT_VERSION >> $GITHUB_OUTPUT
        name: Get project version
        id: project

      - run: |
          set -e

          echo "Latest Github release tag: ${{ steps.release.outputs.version_release }}"
          echo "Project version [EventsHandler.csproj]: ${{ steps.project.outputs.version_project }}"

          compare_versions() {
            local v1=(${1//./ })  # Split LATEST_RELEASE into array
            local v2=(${2//./ })  # Split PROJECT_VERSION into array

            for i in {0..2}; do
              if [[ ${v1[i]:-0} -lt ${v2[i]:-0} ]]; then
                echo "PROJECT_VERSION is higher :: [$1 < $2]"
                echo "✅"
                return 0
              elif [[ ${v1[i]:-0} -gt ${v2[i]:-0} ]]; then
                echo "LATEST_RELEASE is higher :: [$1 > $2]"
                echo "⚠️  Double-check that you've pulled/merged the latest version before continuing." | tee -a $GITHUB_STEP_SUMMARY
                echo "⛔  Project version [$2] needs to be higher than latest release [$1], please adjust the version in [OMC/Infrastructure/WebApi/EventsHandler/EventsHandler.csproj]" | tee -a $GITHUB_STEP_SUMMARY
                return 2
              fi
            done
            echo "Versions are equal :: [$1 == $2]"
            echo "⛔  Project version [$2] needs to be higher than latest release [$1], please adjust the version in [OMC/Infrastructure/WebApi/EventsHandler/EventsHandler.csproj]" | tee -a $GITHUB_STEP_SUMMARY
            return 1
          }

          compare_versions "${{ steps.release.outputs.version_release }}" "${{ steps.project.outputs.version_project }}"
        name: Check project and latest release versions